Repository trpubz/futbol, pull requests merged in 2023-09, with the labels that each got.

#16 Sfeat/game/total scores
  .gitignore
  coverage/.last_run.json
  coverage/.resultset.json
  coverage/.resultset.json.lock
  coverage/assets/0.12.3/DataTables-1.10.20/images/sort_asc.png
  coverage/assets/0.12.3/DataTables-1.10.20/images/sort_asc_disabled.png
  coverage/assets/0.12.3/DataTables-1.10.20/images/sort_both.png
  coverage/assets/0.12.3/DataTables-1.10.20/images/sort_desc.png
  coverage/assets/0.12.3/DataTables-1.10.20/images/sort_desc_disabled.png
  coverage/assets/0.12.3/application.css
  coverage/assets/0.12.3/application.js
  coverage/assets/0.12.3/colorbox/border.png
  coverage/assets/0.12.3/colorbox/controls.png
  coverage/assets/0.12.3/colorbox/loading.gif
  coverage/assets/0.12.3/colorbox/loading_background.png
  coverage/assets/0.12.3/favicon_green.png
  coverage/assets/0.12.3/favicon_red.png
  coverage/assets/0.12.3/favicon_yellow.png
  coverage/assets/0.12.3/images/ui-bg_flat_0_aaaaaa_40x100.png
  coverage/assets/0.12.3/images/ui-bg_flat_75_ffffff_40x100.png
  coverage/assets/0.12.3/images/ui-bg_glass_55_fbf9ee_1x400.png
  coverage/assets/0.12.3/images/ui-bg_glass_65_ffffff_1x400.png
  coverage/assets/0.12.3/images/ui-bg_glass_75_dadada_1x400.png
  coverage/assets/0.12.3/images/ui-bg_glass_75_e6e6e6_1x400.png
  coverage/assets/0.12.3/images/ui-bg_glass_95_fef1ec_1x400.png
  coverage/assets/0.12.3/images/ui-bg_highlight-soft_75_cccccc_1x100.png
  coverage/assets/0.12.3/images/ui-icons_222222_256x240.png
  coverage/assets/0.12.3/images/ui-icons_2e83ff_256x240.png
  coverage/assets/0.12.3/images/ui-icons_454545_256x240.png
  coverage/assets/0.12.3/images/ui-icons_888888_256x240.png
  coverage/assets/0.12.3/images/ui-icons_cd0a0a_256x240.png
  coverage/assets/0.12.3/loading.gif
  coverage/assets/0.12.3/magnify.png
  coverage/index.html
  data/game_teams_mock.csv
  data/games_mock.csv
  lib/runner.rb
  lib/stat_tracker.rb
  spec/.gitkeep
  spec/spec_helper.rb
  spec/stat_tracker_spec.rb
Labels: subfeature

#17 feature/league/high_scores FUT-12
  data/game_teams_mock.csv
  lib/stat_tracker.rb
  spec/stat_tracker_spec.rb
Labels: subfeature

#18 [StatTracker] Add methods to find lowest scoring visitor and home team
  lib/stat_tracker.rb
  spec/stat_tracker_spec.rb
Labels: subfeature

#19 Feat/league FUT-10
  .gitignore
  README.md
  data/game_teams_mock.csv
  data/games_mock.csv
  lib/.keep
  lib/runner.rb
  lib/stat_tracker.rb
  spec/.gitkeep
  spec/spec_helper.rb
  spec/stat_tracker_spec.rb
Labels: enhancement

#23 FUT-15 Add test for #winningest_coach method - checks if the function correc…
  lib/stat_tracker.rb
  spec/stat_tracker_spec.rb
Labels: subfeature

#25 Sfeat/season/accuracy FUT-16
  lib/stat_tracker.rb
  spec/stat_tracker_spec.rb
Labels: subfeature

#29 main has game and league functionality that needs to be based into season
  .gitignore
  README.md
  data/game_teams_mock.csv
  lib/runner.rb
  lib/stat_tracker.rb
  spec/stat_tracker_spec.rb
Labels: enhancement

#31 Feat/season
  lib/stat_tracker.rb
  spec/stat_tracker_spec.rb
Labels: enhancement

#32 Add comment bounds to easily ID query focuses
  lib/stat_tracker.rb
  spec/stat_tracker_spec.rb
Labels: enhancement

#33 Refactor for helper method #average_goals_per interval
  lib/stat_tracker.rb
  lib/stats.rb
  spec/spec_helper.rb
  spec/stat_tracker_spec.rb
  spec/stats_spec.rb
Labels: enhancement

#34 bring in revised logic to main before feature dev
  lib/stat_tracker.rb
  lib/stats.rb
  spec/stats_spec.rb
Labels: enhancement

#38 goal differentials
  lib/stat_tracker.rb
  lib/stats.rb
  spec/stat_tracker_spec.rb
  spec/stats_spec.rb
Labels: enhancement

#39 Add #favorite_opp #rival #head_to_head functionality
  lib/stat_tracker.rb
  lib/stats.rb
  spec/stat_tracker_spec.rb
  spec/stats_spec.rb
Labels: enhancement

#43 Hot fix tp
  lib/stat_tracker.rb
  lib/stats.rb
  spec/stat_tracker_spec.rb
  spec/stats_spec.rb
Labels: bug
